# Copyright (c) 2023, Toyota Motor Corporation
# Copyright (c) 2023, MID Academic Promotions, Inc.
# All rights reserved.

FROM ros:noetic-ros-core-focal

SHELL ["/bin/bash", "-c"]

ENV DEBIAN_FRONTEND noninteractive

RUN apt update && \
    apt install -y git python-is-python3 g++ make libgflags-dev \
    python3-catkin-tools \
    libeigen3-dev libtf-dev \
    ros-noetic-moveit \
    ros-noetic-map-server \
    ros-noetic-dwa-local-planner \
    ros-noetic-move-base \
    ros-noetic-roslint \
    ros-noetic-eigen-conversions \
    ros-noetic-tf-conversions \
    ros-noetic-robot-state-publisher \
    ros-noetic-laser-scan-matcher \
    ros-noetic-depth-image-proc \
    ros-noetic-image-transport-plugins \
    ros-noetic-rviz-imu-plugin \
    ros-noetic-gazebo-msgs \
    ros-noetic-rqt-robot-plugins \
    && \
    apt clean

RUN source /opt/ros/$ROS_DISTRO/setup.bash && \
    mkdir -p /ws/src && \
    cd /ws/src && \
    catkin init && \
    git clone https://github.com/hsr-project/hsrb_description.git && \
    git clone https://github.com/hsr-project/hsrb_meshes.git && \
    git clone https://github.com/hsr-project/hsrb_moveit_config.git && \
    git clone https://github.com/hsr-project/tmc_control_msgs.git && \
    git clone https://github.com/TAMS-Group/bio_ik.git && \
    git clone https://github.com/devrt/mobile-manipulator-tools.git && \
    git clone https://github.com/hsr-project/hsrb_rosnav.git && \
    git clone https://github.com/hsr-project/tmc_gazebo_task_evaluators.git -b feature/gazeboless && \
    git clone https://github.com/iris-ua/iris_lama.git && \
    git clone https://github.com/iris-ua/iris_lama_ros.git && \
    rm -rf mobile-manipulator-tools/cmd_vel_controller && \
    rm -rf mobile-manipulator-tools/loopback_robot_hardware && \
    cd .. && \
    catkin config --install && \
    catkin config --cmake-args -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/opt/ros/$ROS_DISTRO -DCATKIN_ENABLE_TESTING=0 && \
    catkin build && \
    cp -r src/hsrb_rosnav/hsrb_rosnav_config/maps /opt/ros/$ROS_DISTRO/share/hsrb_rosnav_config/maps && \
    cd / && \
    rm -rf /ws

ADD hsr.launch /hsr.launch
ADD hsr-omniverse.rviz /hsr-omniverse.rviz

CMD [ "roslaunch", "/hsr.launch" ]
