version: "2.3"
services:
  ycb-grasp:
    build:
      context: .
      dockerfile: Dockerfile.ycb-grasp
    ipc: host
    network_mode: host
    security_opt:
      - seccomp:unconfined
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    devices:
      - /dev/dri:/dev/dri
    environment:
      - DISPLAY
      - ACCEPT_EULA=Y
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /usr/share/vulkan/icd.d:/usr/share/vulkan/icd.d:ro
      - /usr/share/vulkan/implicit_layer.d:/usr/share/vulkan/implicit_layer.d:ro
      - ${HOME}/.hsr-omniverse/cache/kit:/isaac-sim/kit/cache:rw
      - ${HOME}/.hsr-omniverse/cache/ov:/root/.cache/ov:rw
      - ${HOME}/.hsr-omniverse/cache/pip:/root/.cache/pip:rw
      - ${HOME}/.hsr-omniverse/cache/glcache:/root/.cache/nvidia/GLCache:rw
      - ${HOME}/.hsr-omniverse/cache/computecache:/root/.nv/ComputeCache:rw
      - ${HOME}/.hsr-omniverse/cache/data:/root/.local/share/ov/data:rw
      - ${HOME}/.hsr-omniverse/logs:/root/.nvidia-omniverse/logs:rw
