# Copyright (c) 2023, Toyota Motor Corporation
# Copyright (c) 2023, MID Academic Promotions, Inc.
# All rights reserved.

FROM ros:noetic-ros-core-focal AS ros

FROM nvcr.io/nvidia/isaac-sim:2023.1.1 AS isaac-sim

FROM nvidia/cudagl:11.4.2-base-ubuntu20.04

SHELL ["/bin/bash", "-c"]

ENV DEBIAN_FRONTEND noninteractive

RUN apt update && \
    apt install -y --no-install-recommends \
    curl \
    wget \
    libatomic1 \
    libegl1 \
    libglu1-mesa \
    libgomp1 \
    libsm6 \
    libxi6 \
    libxrandr2 \
    libxt6 \
    libfreetype-dev \
    libfontconfig1 \
    openssl \
    libssl1.1 \
    vulkan-utils \
    && apt -y autoremove \
    && apt clean autoclean

# install ROS dependencies
ENV ROS_DISTRO noetic
COPY --from=ros /ros_entrypoint.sh /
RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -
RUN echo "deb http://packages.ros.org/ros/ubuntu focal main" > /etc/apt/sources.list.d/ros-latest.list
RUN apt update && \
    apt install -y \
    git g++ make python-is-python3 \
    python3-catkin-tools \
    ros-noetic-rospy \
    ros-noetic-tf \
    ros-noetic-actionlib-msgs \
    ros-noetic-geometry-msgs \
    ros-noetic-control-msgs \
    ros-noetic-trajectory-msgs \
    ros-noetic-sensor-msgs \
    ros-noetic-nav-msgs \
    && \
    apt clean
RUN source /opt/ros/$ROS_DISTRO/setup.bash && \
    mkdir -p /ws/src && \
    cd /ws/src && \
    catkin init && \
    git clone https://github.com/hsr-project/tmc_control_msgs.git && \
    cd .. && \
    catkin config --install && \
    catkin config --cmake-args -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/opt/ros/$ROS_DISTRO -DCATKIN_ENABLE_TESTING=0 && \
    catkin build && \
    cd / && \
    rm -rf /ws

COPY --from=isaac-sim /isaac-sim /isaac-sim
RUN mkdir -p /root/.nvidia-omniverse/config
COPY --from=isaac-sim /root/.nvidia-omniverse/config /root/.nvidia-omniverse/config
WORKDIR /isaac-sim

RUN /isaac-sim/python.sh -m pip install rospkg

RUN mkdir /app
WORKDIR /app
ADD hsr.py /app/hsr.py
ADD sample-ros.py /app/sample-ros.py
ADD usd /app/usd

ENV NVIDIA_VISIBLE_DEVICES \
        ${NVIDIA_VISIBLE_DEVICES:-all}
ENV NVIDIA_DRIVER_CAPABILITIES all

RUN rm -rf /etc/vulkan

ENTRYPOINT [ "/ros_entrypoint.sh" ]
CMD [ "/isaac-sim/python.sh", "/app/sample-ros.py"]
