# Copyright (c) 2023, Toyota Motor Corporation
# Copyright (c) 2023, MID Academic Promotions, Inc.
# All rights reserved.

FROM ros:humble-ros-core-jammy

SHELL ["/bin/bash", "-c"]

ENV DEBIAN_FRONTEND noninteractive

RUN rm -f /etc/apt/apt.conf.d/docker-clean; echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt update && \
    apt install -y git python-is-python3 g++ make libgflags-dev \
    python3-colcon-common-extensions \
    libeigen3-dev \
    libpoco-dev \
    libboost-system-dev \
    libboost-filesystem-dev \
    libsdl1.2-dev \
    libsdl-image1.2-dev \
    ros-humble-rclpy \
    ros-humble-rosidl-default-generators \
    ros-humble-tf-transformations \
    ros-humble-tf2 \
    ros-humble-tf2-msgs \
    ros-humble-tf2-geometry-msgs \
    ros-humble-actionlib-msgs \
    ros-humble-geometry-msgs \
    ros-humble-control-msgs \
    ros-humble-trajectory-msgs \
    ros-humble-sensor-msgs \
    ros-humble-nav-msgs \
    ros-humble-vision-msgs \
    ros-humble-gazebo-msgs \
    ros-humble-topic-tools \
    ros-humble-joint-state-publisher \
    ros-humble-moveit \
    ros-humble-moveit-ros-move-group \
    ros-humble-moveit-ros-perception \
    ros-humble-pinocchio \
    ros-humble-nav2-map-server \
    ros-humble-nav2-bringup \
    ros-humble-navigation2 \
    ros-humble-robot-state-publisher \
    ros-humble-depth-image-proc \
    ros-humble-image-transport-plugins \
    ros-humble-image-proc \
    ros-humble-depth-image-proc \
    ros-humble-rviz-imu-plugin \
    ros-humble-rqt-robot-steering \
    ros-humble-rqt-tf-tree \
    ros-humble-controller-interface \
    ros-humble-realtime-tools \
    ros-humble-action-tutorials-interfaces \
    ros-humble-example-interfaces \
    ros-humble-diagnostic-updater \
    ros-humble-std-srvs \
    libode-dev \
    ipython3 \
    python3-stl

RUN source /opt/ros/$ROS_DISTRO/setup.bash && \
    mkdir -p /ws/src && \
    cd /ws/src && \
    git clone -b humble https://github.com/hsr-project/hsrb_description.git && \
    git clone -b humble https://github.com/hsr-project/hsrb_meshes.git && \
    git clone -b humble https://github.com/hsr-project/tmc_common.git && \
    git clone -b humble https://github.com/hsr-project/hsr_common.git && \
    git clone -b humble https://github.com/hsr-project/tmc_drivers.git && \
    git clone -b humble https://github.com/hsr-project/tmc_database.git && \
    git clone -b humble https://github.com/hsr-project/tmc_manipulation_base.git && \
    git clone -b humble https://github.com/hsr-project/tmc_manipulation.git && \
    git clone -b humble https://github.com/hsr-project/tmc_manipulation_planner.git && \
    git clone -b humble https://github.com/hsr-project/hsrb_manipulation.git && \
    git clone -b humble https://github.com/hsr-project/hsrb_moveit_plugins.git && \
    git clone -b humble https://github.com/hsr-project/hsrb_moveit_config.git && \
    git clone -b humble https://github.com/hsr-project/tmc_common_msgs.git && \
    git clone -b humble https://github.com/hsr-project/tmc_realtime_control.git && \
    git clone -b humble https://github.com/hsr-project/tmc_navigation.git && \
    git clone -b humble https://github.com/hsr-project/hsrb_rosnav.git && \
    git clone -b humble https://github.com/hsr-project/hsrb_robot.git && \
    git clone -b ros2_csm_eigen https://github.com/AlexKaravaev/csm.git && \
    git clone -b main https://github.com/AlexKaravaev/ros2_laser_scan_matcher.git && \
    git clone -b humble https://github.com/hsr-project/tmc_voice.git && \
    git clone -b humble https://github.com/hsr-project/hsrb_launch.git && \
    git clone -b humble https://github.com/hsr-project/hsrb_interfaces.git && \
    git clone -b feature/ros2 https://github.com/hsr-project/tmc_gazebo_task_evaluators.git && \
    git clone -b feature/ros2 https://github.com/hsr-project/tmc_wrs_gazebo.git && \
    rm -rf tmc_drivers/tmc_pgr_camera && \
    rm -rf tmc_voice/tmc_talk_hoya_py && \
    cd .. && \
    colcon build

RUN curl -sSL https://raw.githubusercontent.com/NVIDIA-Omniverse/IsaacSim-ros_workspaces/main/humble_ws/fastdds.xml -o /fastdds.xml
ENV FASTRTPS_DEFAULT_PROFILES_FILE /fastdds.xml

RUN curl -sSL https://github.com/hsr-project/hsrb_rosnav/raw/refs/heads/master/hsrb_rosnav_config/maps/white_space/map.yaml -o /map.yaml
RUN curl -sSL https://github.com/hsr-project/hsrb_rosnav/raw/refs/heads/master/hsrb_rosnav_config/maps/white_space/white_space.pgm -o /white_space.pgm

ADD hsr.launch.py /hsr.launch.py
ADD hsrb_relay_topics.launch.xml /hsrb_relay_topics.launch.xml
ADD hsrb_sensor_frames.launch.xml /hsrb_sensor_frames.launch.xml
ADD hsr-omniverse.rviz /hsr-omniverse.rviz

ADD ros_entrypoint.sh.ros2 /ros_entrypoint.sh

CMD [ "ros2", "launch", "/hsr.launch.py" ]
#CMD [ "tail", "-f", "/dev/null" ]
