FROM ros:noetic-ros-core-focal AS ros
FROM nvcr.io/nvidia/isaac-sim:4.5.0 AS isaac-sim
FROM nvidia/cuda:12.2.0-devel-ubuntu20.04

SHELL ["/bin/bash", "-c"]
ENV DEBIAN_FRONTEND=noninteractive
ENV ROS_DISTRO=noetic
ENV NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=all
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl wget gnupg ca-certificates \
    libatomic1 libegl1 libglu1-mesa libgomp1 libsm6 libxi6 libxrandr2 libxt6 \
    libfreetype-dev libfontconfig1 openssl libssl1.1 \
    git g++ make python-is-python3 \
    vulkan-utils \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY --from=ros /ros_entrypoint.sh /
RUN curl -fsSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add - && \
    echo "deb http://packages.ros.org/ros/ubuntu focal main" > /etc/apt/sources.list.d/ros-latest.list

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-catkin-tools  \ 
    ros-noetic-rosbash \
    ros-noetic-rospy \
    ros-noetic-rosgraph \
    ros-noetic-xacro \
    ros-noetic-tf \
    ros-noetic-actionlib-msgs \
    ros-noetic-geometry-msgs \
    ros-noetic-control-msgs \
    ros-noetic-trajectory-msgs \
    ros-noetic-sensor-msgs \
    ros-noetic-nav-msgs \
    ros-noetic-gazebo-msgs \
    ros-noetic-std-msgs \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN source /opt/ros/${ROS_DISTRO}/setup.bash && \
    mkdir -p /ws/src && cd /ws/src && \
    catkin init && \
    git clone https://github.com/hsr-project/tmc_control_msgs.git && \
    git clone -b feature/modularrandomizer https://github.com/hsr-project/tmc_wrs_gazebo.git && \
    cd /ws && \
    catkin config --install && \
    catkin config --cmake-args -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/opt/ros/${ROS_DISTRO} -DCATKIN_ENABLE_TESTING=0 && \
    catkin build && \
    rm -rf /ws

COPY --from=isaac-sim /isaac-sim /isaac-sim
RUN mkdir -p /root/.nvidia-omniverse/config
COPY --from=isaac-sim /root/.nvidia-omniverse/config /root/.nvidia-omniverse/config
#COPY --from=isaac-sim /etc/vulkan/icd.d/nvidia_icd.json /etc/vulkan/icd.d/nvidia_icd.json
#COPY --from=isaac-sim /etc/vulkan/icd.d/nvidia_icd.json /etc/vulkan/implicit_layer.d/nvidia_layers.json

WORKDIR /isaac-sim
RUN /isaac-sim/python.sh -m pip install rospkg

WORKDIR /app
COPY hsr.py /app/hsr.py
COPY sample-ros.py /app/sample-ros.py

COPY OgnROS1ActionFollowJointTrajectory.py /app/OgnROS1ActionFollowJointTrajectory.py
COPY OgnROS1ActionGripperCommand.py /app/OgnROS1ActionGripperCommand.py

COPY usd /app/usd

ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["/isaac-sim/python.sh", "/app/sample-ros.py"]
