# Copyright (c) 2023, Toyota Motor Corporation
# Copyright (c) 2023, MID Academic Promotions, Inc.
# All rights reserved.
version: "2.3"
services:
  ros2:
    build:
      context: ..
      dockerfile: env_docker/Dockerfile.ros2
    ipc: host
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=graphics
      - CYCLONEDDS_URI=${CYCLONEDDS_URI:-file:///cyclonedds.xml}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
    volumes:
      - ../assets/cyclonedds.pc.xml:/cyclonedds.pc.xml:ro
    security_opt:
      - seccomp:unconfined
  cacheproxy:
    build:
      context: ..
      dockerfile: env_docker/Dockerfile.cacheproxy
    network_mode: host
  isaacsim:
    build:
      context: ..
      dockerfile: env_docker/Dockerfile.isaacsim-ros2
    ipc: host
    network_mode: host
    security_opt:
      - seccomp:unconfined
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    devices:
      - /dev/dri:/dev/dri
    environment:
      - DISPLAY
      - ACCEPT_EULA=Y
      - http_proxy=http://127.0.0.1:3128
      - NVIDIA_VISIBLE_DEVICES=all
      - HSR_ROS_VERSION=2
      - CYCLONEDDS_URI=${CYCLONEDDS_URI:-file:///cyclonedds.xml}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
    volumes:
      - ../assets/cyclonedds.pc.xml:/cyclonedds.pc.xml:ro
      - ../scripts/launch_isaacsim.py:/app/launch_isaacsim.py:ro
      - ../worlds:/app/worlds:ro
      #- /usr/share/vulkan/icd.d:/usr/share/vulkan/icd.d:ro
      #- /usr/share/vulkan/implicit_layer.d:/usr/share/vulkan/implicit_layer.d:ro
      - ${HOME}/.hsr-omniverse/cache/kit:/isaac-sim/kit/cache:rw
      - ${HOME}/.hsr-omniverse/cache/ov:/root/.cache/ov:rw
      - ${HOME}/.hsr-omniverse/cache/pip:/root/.cache/pip:rw
      - ${HOME}/.hsr-omniverse/cache/glcache:/root/.cache/nvidia/GLCache:rw
      - ${HOME}/.hsr-omniverse/cache/computecache:/root/.nv/ComputeCache:rw
      - ${HOME}/.hsr-omniverse/cache/data:/root/.local/share/ov/data:rw
      - ${HOME}/.hsr-omniverse/logs:/root/.nvidia-omniverse/logs:rw
    depends_on:
      - cacheproxy
