# Copyright (c) 2023, Toyota Motor Corporation
# Copyright (c) 2023, MID Academic Promotions, Inc.
# All rights reserved.

FROM ros:humble-ros-core-jammy AS ros

#FROM nvcr.io/nvidia/isaac-sim:2023.1.1
FROM nvcr.io/nvidia/isaac-sim:4.5.0 AS isaac-sim


SHELL ["/bin/bash", "-c"]

ENV DEBIAN_FRONTEND noninteractive

RUN apt update && \
    apt install -y --no-install-recommends \
    curl \
    wget \
    && apt -y autoremove \
    && apt clean autoclean

# install ROS dependencies
ENV ROS_DISTRO humble
#COPY --from=ros /ros_entrypoint.sh /
RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
RUN echo "deb [arch=amd64 signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu jammy main" > /etc/apt/sources.list.d/ros2.list

RUN rm -f /etc/apt/apt.conf.d/docker-clean; echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt update && \
    apt install -y \
    git g++ make python-is-python3 python3-pip \
    python3-colcon-common-extensions \
    libeigen3-dev \
    libpoco-dev \
    libboost-system-dev \
    libboost-filesystem-dev \
    ros-humble-ros2cli \
    ros-humble-ros2cli-common-extensions \
    ros-humble-rclpy \
    ros-humble-xacro \
    ros-humble-rosidl-default-generators \
    ros-humble-rclpy \
    ros-humble-tf-transformations \
    ros-humble-tf2 \
    ros-humble-tf2-msgs \
    ros-humble-tf2-geometry-msgs \
    ros-humble-tf2-ros-py \
    ros-humble-actionlib-msgs \
    ros-humble-geometry-msgs \
    ros-humble-control-msgs \
    ros-humble-trajectory-msgs \
    ros-humble-sensor-msgs \
    ros-humble-nav-msgs \
    ros-humble-vision-msgs \
    ros-humble-gazebo-msgs \
    ros-humble-moveit-msgs \
    ros-humble-controller-interface \
    ros-humble-realtime-tools \
    ros-humble-diagnostic-updater \
    ros-humble-std-srvs \
    ros-humble-action-tutorials-interfaces \
    ros-humble-example-interfaces \
    ros-humble-angles \
    ros-humble-urdf \
    ros-humble-rmw-cyclonedds-cpp
RUN /isaac-sim/python.sh -m pip install transforms3d

RUN source /opt/ros/$ROS_DISTRO/setup.bash && \
    mkdir -p /ws/src && \
    cd /ws/src && \
    git clone -b humble https://github.com/hsr-project/tmc_common_msgs.git && \
    git clone -b humble https://github.com/hsr-project/tmc_common.git && \
    git clone -b humble https://github.com/hsr-project/tmc_drivers.git && \
    git clone -b humble https://github.com/hsr-project/tmc_realtime_control.git && \
    git clone -b ignition/humble https://github.com/ry0hei-kobayashi/tmc_wrs_gazebo.git && \
    #git clone -b feature/ros2 https://github.com/hsr-project/tmc_wrs_gazebo.git && \
    #git clone -b feature/ros2 https://github.com/hsr-project/tmc_gazebo_task_evaluators.git && \
    rm -rf hsrb_launch/hsrb_robot_launch && \
    rm -rf hsrb_gazebo_launch/tmc_grid_map_server && \
    rm -rf hsrb_simulator/hsrb_rviz_simulator && \
    rm -rf tmc_drivers/tmc_pgr_camera && \
    cd .. && \
    colcon build
ADD assets/ros_entrypoint.sh.ros2 /ros_entrypoint.sh

# RUN curl -sSL https://raw.githubusercontent.com/NVIDIA-Omniverse/IsaacSim-ros_workspaces/main/humble_ws/fastdds.xml -o /fastdds.xml
# ENV FASTRTPS_DEFAULT_PROFILES_FILE /fastdds.xml
COPY assets/cyclonedds.xml /cyclonedds.xml
ENV RMW_IMPLEMENTATION=rmw_cyclonedds_cpp

WORKDIR /isaac-sim

RUN mkdir /app
WORKDIR /app
ADD scripts/hsr.py /app/hsr.py
ADD scripts/hsr_hsrc_ex.py /app/hsr_hsrc_ex.py
ADD scripts/ros2_bridge.py /app/ros2_bridge.py
ADD scripts/launch_isaacsim.py /app/launch_isaacsim.py
ADD scripts/construct_environment.py /app/construct_environment.py
ADD scripts/object_placement.py /app/object_placement.py
ADD scripts/people_spawn.py /app/people_spawn.py
ADD scripts/furniture_spawn.py /app/furniture_spawn.py
ADD scripts/dressing_presets.py /app/dressing_presets.py
ADD scene_dressing /app/scene_dressing
ADD configs /app/configs
ADD usd /app/usd
ADD worlds /app/worlds
# プレースホルダテクスチャを焼き込んで、マウントなしでも動くようにする
ADD configs/textures /data/textures

ENV NVIDIA_VISIBLE_DEVICES \
        ${NVIDIA_VISIBLE_DEVICES:-all}
ENV NVIDIA_DRIVER_CAPABILITIES all

ENV PYTHONUNBUFFERED 1

ENTRYPOINT [ "/ros_entrypoint.sh" ]

CMD [ "/isaac-sim/python.sh", "/app/launch_isaacsim.py"]
